name: Teste_auto_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make re
    - run: ./minishell
    - run: cd libraries
    - run: cd ..
    - run: pwd
    - run: echo "''" oi
    - run: ARG=TMP
    - run: echo $ARG
    - run: ARG=ENV
    - run: echo $ARG
    - run: export ARG
    - run: echo $ARG
    - run: ARG=HASH
    - run: echo $ARG
        
        
