name: Teste_auto_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-gcc@d04208cef6e985db0830428975fc2ab3f28d89a1
      uses: egor-tensin/setup-gcc@v1
      with:
        # GCC version to install
        version: # optional, default is latest
        # Target platform
        platform: # optional, default is x64
        # Set up cc/gcc/c++/g++ executables
        cc: 'gcc'
    - name: make
      run: make
    - name: make check
      run: make re
    - run: ./minishell
    - run: cd libraries
    - run: cd ..
    - run: pwd
    - run: echo "''" oi
    - run: ARG=TMP
    - run: echo $ARG
    - run: ARG=ENV
    - run: echo $ARG
    - run: export ARG
    - run: echo $ARG
    - run: ARG=HASH
    - run: echo $ARG
        
        
