name: Teste_auto_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make re
    - run: ./minishell
          cd libraries
          cd ..
          pwd
          echo "''" oi
          ARG=TMP
          echo $ARG
          ARG=ENV
          echo $ARG
          export ARG
          echo $ARG
          ARG=HASH
          echo $ARG
        
        
